version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - JWT_SECRET=My!@!Se3cr8tH4sh3
      - CLOUD_NAME=almacenceliacoapi
      - CLOUD_API_KEY=112718242582838
      - CLOUD_SECRET_KEY=dRhozsyc0zBM2nOg4ScHNCJnWd8 